# Generated by Django 6.0.3 on 2026-03-11 10:53

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.core.model_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_project_projectartifact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(default=apps.core.model_utils.generate_random_key, max_length=64, unique=True)),
                ('scopes', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_api_keys', to='core.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAPIAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('project.create', 'Create project'), ('project.list', 'List projects'), ('project.get', 'Get project'), ('project.status', 'Get project status')], max_length=32)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('method', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('key_type', models.CharField(blank=True, default='', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_api_audit_logs', to='core.profile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_audit_logs', to='core.project')),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='api.projectapikey')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
