# Generated by Forge on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectapiauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("project.create", "Create project"),
                    ("project.list", "List projects"),
                    ("project.get", "Get project"),
                    ("project.status", "Get project status"),
                    ("project.download", "Download project artifact"),
                ],
                max_length=32,
            ),
        ),
    ]
