name: Deploy Prod

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    name: Deploy ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Server
            process_type: server
            app_name: djass
            image_name: ghcr.io/lvtd-llc/djass
            token_secret: APP_TOKEN
          - name: Workers
            process_type: worker
            app_name: djass-workers
            image_name: ghcr.io/lvtd-llc/djass-workers
            token_secret: WORKERS_APP_TOKEN
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: deployment/Dockerfile
          tags: ${{ matrix.image_name }}
          build-args: |
            DJASS_PROCESS_TYPE=${{ matrix.process_type }}

      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@main
        with:
          server: ${{ secrets.CAPROVER_SERVER }}
          app: ${{ matrix.app_name }}
          token: ${{ secrets[matrix.token_secret] }}
          image: ${{ matrix.image_name }}
